<?php include 'header.php'; ?> <html>
		<title>Présentation</title>
	      <div class="main">
	      	      <div class="shop_top">
	      			<div class="container">

<h3 class="western" style="color: #FF4500">Pr&eacute;sentation de la Maison des Ligues de Lorraine</h3>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">La Maison des Ligues de Lorraine (M2L) a pour mission de fournir des espaces et des services aux diff&eacute;rentes ligues sportives r&eacute;gionales et &agrave; d&rsquo;autres structures h&eacute;berg&eacute;es. La M2L est une structure financ&eacute;e par le Conseil R&eacute;gional de Lorraine dont l'administration est d&eacute;l&eacute;gu&eacute;e au Comit&eacute; R&eacute;gional Olympique et Sportif de Lorraine (CROSL).</span></p>
<p class="western" align="justify">&nbsp;</p>
<h3 class="western"><a name="__RefHeading___Toc294250834"></a>Interview de son directeur, M. Lucien Sapin.</h3>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. M. Sapin, merci de nous accueillir dans ces locaux tous neufs et superbes de l&rsquo;extension de la Maison des Ligues de Lorraine. Pouvez-vous nous dire quel est le statut juridique de cette maison, et quelles sont ses sources de financement ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. La Maison des Ligues est un &eacute;tablissement du Conseil R&eacute;gional. Ce n&rsquo;est pas une entit&eacute; juridique en propre. Elle est financ&eacute;e &agrave; 100 % (pour son fonctionnement et pour la construction r&eacute;cente de l&rsquo;extension des b&acirc;timents C et D) par le Conseil R&eacute;gional et sans aucune participation du Conseil G&eacute;n&eacute;ral de Meurthe et Moselle, bien qu&rsquo;elle abrite un certain nombre de comit&eacute;s d&eacute;partementaux. Une convention de cogestion a &eacute;t&eacute; pass&eacute;e entre le Conseil R&eacute;gional et le Comit&eacute; R&eacute;gional Olympique et Sportif de Lorraine pour la gestion de l&rsquo;outil &laquo; Maison des Ligues &raquo;. Le CROSL&nbsp;est une association financ&eacute;e par le minist&egrave;re via le CNDS (Centre National de D&eacute;veloppement du Sport).</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Pourquoi l&rsquo;h&eacute;bergement de comit&eacute;s d&eacute;partementaux perdure-t-il ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. Lors de la reprise de la Maison des Ligues en 2000 par la R&eacute;gion Lorraine et la n&eacute;gociation qui en a suivi, le mouvement sportif a d&eacute;fendu la pr&eacute;sence des comit&eacute;s d&eacute;partementaux dans les locaux existants. Cette pr&eacute;sence est remise en question r&eacute;guli&egrave;rement, mais il est probable que rien ne sera fait avant la r&eacute;forme des territoires et la &laquo; fusion &raquo; des conseillers r&eacute;gionaux et g&eacute;n&eacute;raux en conseillers territoriaux.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Quelles sont les structures que vous h&eacute;bergez ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. La Maison h&eacute;berge la majorit&eacute; des ligues sportives r&eacute;gionales, de la ligue de tennis (la plus grosse, qui emploie 8 personnes) &agrave; des ligues de sports qui n&rsquo;ont pas d&rsquo;employ&eacute;s permanents, comme le bowling ou la plong&eacute;e sous-marine. La ligue de football occupe 2000 m</span><sup><span style="font-family: Calibri, sans-serif;">2</span></sup><span style="font-family: Calibri, sans-serif;">&nbsp;de bureaux dans la banlieue de Nancy et ne sera probablement jamais h&eacute;berg&eacute;e dans nos locaux. Nous h&eacute;bergeons &eacute;galement, comme je vous le disais, quelques comit&eacute;s d&eacute;partementaux, ainsi que le CROSL et sa d&eacute;clinaison d&eacute;partementale&nbsp;: le CDOS (Comit&eacute; D&eacute;partemental Olympique et Sportif).</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Existe-il une convention d&rsquo;h&eacute;bergement ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. Oui, la convention initiale date de 2003. On parle de convention d'occupation du domaine public. Elle est en cours de r&eacute;vision, puisque les locaux ont &eacute;t&eacute; agrandis et que de nouveaux services sont apparus. La nouvelle version sera disponible l&rsquo;&eacute;t&eacute; prochain, elle est assortie d&rsquo;un r&egrave;glement int&eacute;rieur. Dans cette convention figure notamment l&rsquo;obligation d&rsquo;assurances en responsabilit&eacute; civile des structures h&eacute;berg&eacute;es. Je peux vous donner un exemple de cette convention.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Quelle est la nature du &laquo; loyer &raquo; demand&eacute; aux &laquo; locataires &raquo; ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R.</span> <span style="font-family: Calibri, sans-serif;">On est davantage sur le principe d&rsquo;une participation aux charges de gestion courante, plut&ocirc;t que sur celui d&rsquo;un loyer &agrave; proprement parler. On est sur la base de 5&euro; par m</span><sup><span style="font-family: Calibri, sans-serif;">2</span></sup><span style="font-family: Calibri, sans-serif;">&nbsp;et par mois, avec une augmentation pr&eacute;vue d&rsquo;un euro dans les mois &agrave; venir. Un appel est effectu&eacute; sur cette base forfaitaire en d&eacute;but d&rsquo;ann&eacute;e et une r&eacute;gularisation pourrait &ecirc;tre demand&eacute;e en fin d&rsquo;ann&eacute;e en cas de d&eacute;passement de la consommation &eacute;lectrique, mais cela n&rsquo;a jamais &eacute;t&eacute; fait jusqu&rsquo;&agrave; maintenant.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">La r&eacute;alit&eacute; des charges &agrave; r&eacute;partir est difficile &agrave; cerner. Si vous prenez par exemple le poste &laquo; nettoyage des locaux &raquo; : celui-ci fait l&rsquo;objet d&rsquo;un appel d&rsquo;offres du Conseil R&eacute;gional pour l&rsquo;ensemble de ses implantations. Il est difficile de savoir quelle est la part affect&eacute;e &agrave; la Maison et encore moins la part qui incomberait aux structures h&eacute;berg&eacute;es. Il n&rsquo;y a pas eu jusqu&rsquo;&agrave; maintenant de comptabilit&eacute; analytique dans ce domaine.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">Les charges comprennent le chauffage, l&rsquo;&eacute;lectricit&eacute;, le nettoyage, l&rsquo;acc&egrave;s Internet&nbsp;; le t&eacute;l&eacute;phone n&rsquo;en fait pas partie. Les consommations sont refactur&eacute;es chaque trimestre aux structures h&eacute;berg&eacute;es. Depuis la mise en place de la t&eacute;l&eacute;phonie IP fin 2010, on peut conna&icirc;tre les consommations poste par poste et m&ecirc;me structure par structure. Les appareils t&eacute;l&eacute;phoniques font partie de la prestation d&rsquo;h&eacute;bergement, comme la fourniture de trois badges pour l&rsquo;entr&eacute;e et de deux cl&eacute;s par bureau.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western"><span style="font-family: Calibri, sans-serif;"><em>Q. Qui facture les prestations d&rsquo;h&eacute;bergement et les prestations annexes aux structures ?<br /></em></span></p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. Nous sommes dans le cadre d&rsquo;une convention de cogestion entre le CROSL et la R&eacute;gion Lorraine, mais il n&rsquo;est pas question que le CROSL facture l&rsquo;utilisation de ressources appartenant &agrave; la R&eacute;gion, comme les locaux ou le t&eacute;l&eacute;phone par exemple. Par contre, le CROSL facture des prestations annexes r&eacute;alis&eacute;es sur des &eacute;quipements lui appartenant, comme l&rsquo;affranchissement et les tirages sur les photocopieurs num&eacute;riques.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Comment fonctionne le syst&egrave;me de r&eacute;servation des salles ressources, comme les salles de r&eacute;unions, l&rsquo;amphith&eacute;&acirc;tre ou encore la nouvelle salle de convivialit&eacute; ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. Concernant l&rsquo;amphi, il y a &frac12; journ&eacute;e gratuite par an pour chaque ligue et comit&eacute; d&eacute;partemental (CD). Les salles de r&eacute;unions d&rsquo;&eacute;tage sont mises librement &agrave; la disposition des occupants de l&rsquo;&eacute;tage. Les salles de r&eacute;unions sont r&eacute;servables via l&rsquo;Intranet, avec diff&eacute;rents services associ&eacute;s dont certains sont payants. Il existe quatre niveaux de tarification. En 2009, nous avons re&ccedil;u 2732 r&eacute;unions et 47316 personnes ont assist&eacute; &agrave; ces r&eacute;unions.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Quels sont ces niveaux de tarification ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. Les ligues peuvent r&eacute;server sans payer jusqu&rsquo;&agrave; concurrence de six r&eacute;servations par an, hors amphi. Les clubs sportifs et les comit&eacute;s d&eacute;partementaux ont un premier niveau de tarification. Les associations, les lyc&eacute;es ou encore les coll&egrave;ges sont sur un second niveau de tarification. Enfin, tous les autres organismes, y compris des soci&eacute;t&eacute;s priv&eacute;es, sont sur le niveau de tarification le plus haut. Pour toutes les structures qui ne sont pas h&eacute;berg&eacute;es, les locaux &eacute;tant publics, il faut faire signer entre les parties une &laquo; convention d&rsquo;occupation temporaire &raquo;. La r&eacute;servation se fait dans l&rsquo;Intranet directement pour les structures h&eacute;berg&eacute;es ou par le secr&eacute;tariat pour une demande ext&eacute;rieure. Les informations sont ensuite transmises au Conseil R&eacute;gional qui &eacute;met un &laquo; titre de paiement &raquo;, c&rsquo;est-&agrave;-dire une facture d&rsquo;occupation de locaux. Ces titres sont envoy&eacute;s directement par le Conseil R&eacute;gional aux utilisateurs.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Pouvez-vous nous parler du personnel de la M2L et de leurs missions ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. Les personnes qui travaillent ici sont de diff&eacute;rentes cat&eacute;gories. Il y a d&rsquo;abord ceux que j&rsquo;appelle les &laquo;professionnels&raquo;. Il y a deux employ&eacute;s du Conseil R&eacute;gional (des factotums). Il y a sept ETP (&Eacute;quivalents Temps Plein) employ&eacute;s par le CROSL ; il y a le personnel des prestataires (gardiennage, m&eacute;nage) et les salari&eacute;s des ligues. Ensuite, il y a les b&eacute;n&eacute;voles qui sont les &eacute;lus des associations : CROSL, CDOS, ligues, comit&eacute;s d&eacute;partementaux. Il y a &eacute;galement les &eacute;lus du Conseil R&eacute;gional et enfin tous les autres : visiteurs, stagiaires, etc.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Quelles sont les missions des personnels &laquo; R&eacute;gion &raquo; et &laquo; CROSL &raquo; ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. Nous avons 2,25 ETP &laquo; r&eacute;gion &raquo;, les deux factotums dont je vous parlais pr&eacute;c&eacute;demment, et moi, qui suis employ&eacute;, pour un quart de mon poste, par le conseil r&eacute;gional. Cela s&rsquo;explique par le fait que je ne pourrais avoir logiquement d&rsquo;autorit&eacute; sur les personnels &laquo; R&eacute;gion &raquo; si je n&rsquo;en fais pas partie moi-m&ecirc;me.</span></p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">Les autres ETP du CROSL sont les suivants :</span></p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">- 0,75 ETP pour le poste de direction, comme je viens de vous dire</span></p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">- 0,8 ETP sur le suivi du Plan Impact Emploi Association</span></p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">- 0,5 ETP sur la gestion : facturation du CROSL et du Conseil R&eacute;gional, comptabilit&eacute;, gestion des r&eacute;servations</span></p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">- 1 ETP sur la formation, la communication et le secr&eacute;tariat</span></p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">- 0,80 ETP sur le domaine &laquo; SAPHIR &raquo;, c&rsquo;est-&agrave;-dire les aspects m&eacute;dicaux li&eacute;s aux mouvements sportifs</span></p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">- 1 ETP d&rsquo;infographiste et gestion des photocopieuses num&eacute;riques.</span></p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">- 1 ETP sur l&rsquo;accueil qui va bient&ocirc;t passer en deux fois 0,5 ETP.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Vous parliez du Plan Impact Emploi Association. De quoi s&rsquo;agit-il ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. Ce dispositif r&eacute;pond &agrave; la volont&eacute; des pouvoirs publics de d&eacute;velopper, en faveur des associations, une gamme de simplifications et de services en mati&egrave;re d'aide &agrave; l'emploi, comme la gestion des paies et l'assistance comptable. Ce service est offert &agrave; toutes les associations de moins de 10 ETP : clubs sportifs, associations culturelles, etc.&nbsp;</span><span style="font-family: Calibri, sans-serif;"><em>Impact Emploi</em></span><span style="font-family: Calibri, sans-serif;">&nbsp;est un logiciel d&eacute;velopp&eacute; par l' URSSAF qui permet d'&eacute;tablir le bulletin de salaire et de fournir l'ensemble des d&eacute;clarations sociales et fiscales, qu'elles soient mensuelles, trimestrielles ou annuelles. Tout cela, simplement &agrave; partir de quelques donn&eacute;es : le nombre d'heures travaill&eacute;es, leur nature et les &eacute;l&eacute;ments de r&eacute;mun&eacute;ration bruts ou nets (salaire, prime, avantages en nature, indemnit&eacute;s de frais, etc.). Ce logiciel est confi&eacute; gratuitement &agrave; des tiers de confiance qui ex&eacute;cutent les op&eacute;rations pour le compte de l'association. Le tiers de confiance est souvent une structure qui f&eacute;d&egrave;re le milieu dans lequel &eacute;volue l'association. Ainsi, le CROSL a re&ccedil;u le label &laquo; CRIB &raquo; (Centre de Ressources et d&rsquo;Information des B&eacute;n&eacute;voles) pour devenir tiers de confiance pour l&rsquo;URSSAF qui met &agrave; notre disposition ce fameux logiciel. Nous demandons 60 &euro; de cotisation annuelle par association et nous facturons 5 &euro; par fiche de paie. Nous produisons bien &eacute;videmment toute la panoplie l&eacute;gale de documents : r&eacute;capitulatifs p&eacute;riodiques, d&eacute;clarations URSSAF et ASSEDIC, organismes de retraite. Nous pouvons g&eacute;rer des virements automatiques : pr&eacute;l&egrave;vement sur le compte des associations et versement sur le compte des salari&eacute;s ou encore pr&eacute;l&egrave;vement direct sur les comptes des associations au cr&eacute;dit des organismes sociaux. En 2009, nous avions 72 associations abonn&eacute;es pour un total de 332 salari&eacute;s, ce qui repr&eacute;sentait 2,8 millions d&rsquo;euros de masse salariale, soit 15 % de la masse salariale totale du sport lorrain.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">En tant que centre labellis&eacute; &laquo; CRIB &raquo; nous apportons &eacute;galement des conseils aux associations qui emploient du personnel. Ces conseils portent sur le respect de la l&eacute;gislation, sur le remboursement des d&eacute;placements, sur les litiges &eacute;ventuels. Nous disposons de toute l&rsquo;information utile pour mener &agrave; bien cette mission de conseil.</span></p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><span style="font-size: xx-small;"><br /></span></span><span style="font-family: Calibri, sans-serif;">En ce moment, sous l&rsquo;impulsion du minist&egrave;re, nous &oelig;uvrons au d&eacute;veloppement de l&rsquo;usage du ch&egrave;que emploi associatif.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Comment sont g&eacute;r&eacute;s les appels d&rsquo;offres aux prestataires ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. Le CROSL n&rsquo;est pas soumis &agrave; l&rsquo;obligation des march&eacute;s publics, contrairement &agrave; la R&eacute;gion. Les appels d&rsquo;offres &laquo; R&eacute;gion &raquo; sont pilot&eacute;s directement par les services du Conseil R&eacute;gional. Les appels d&rsquo;offres du CROSL sont g&eacute;r&eacute;s directement par moi. En g&eacute;n&eacute;ral, nous faisons &eacute;tablir quelques devis et nous choisissons nos prestataires sur la base de ces devis. Pour les nombreux projets concernant l&rsquo;informatique, je me fais assister d&rsquo;un informaticien b&eacute;n&eacute;vole, membre du bureau du CROSL. La r&eacute;alisation des projets est en g&eacute;n&eacute;ral confi&eacute;e &agrave; des prestataires locaux. Notre informaticien b&eacute;n&eacute;vole ne s&rsquo;occupe que de petits travaux quotidiens d&rsquo;assistance aux utilisateurs.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Avez-vous un exemple de projet, l&rsquo;Intranet ou le r&eacute;seau d&rsquo;affichage num&eacute;rique ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. C&rsquo;est typiquement un projet mixte. Les t&eacute;l&eacute;viseurs du r&eacute;seau d&rsquo;information num&eacute;rique ont &eacute;t&eacute; fournis par la R&eacute;gion dans le cadre d&rsquo;un appel d&rsquo;offre public. Le syst&egrave;me qui fait para&icirc;tre les informations sur les afficheurs a fait l&rsquo;objet d&rsquo;une consultation et c&rsquo;est la soci&eacute;t&eacute; qui nous avait fourni l&rsquo;Intranet, il y a quelques ann&eacute;es, qui a &eacute;t&eacute; choisie pour d&eacute;velopper ce logiciel qui r&eacute;cup&egrave;re directement les donn&eacute;es du syst&egrave;me de r&eacute;servation des salles. Il n&rsquo;est donc pas n&eacute;cessaire de ressaisir les informations sur l&rsquo;utilisation des salles.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. Quelles sont les autres fonctions de l&rsquo;Intranet ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. Comme vous le savez, c&rsquo;est un Intranet accessible &eacute;galement de l&rsquo;ext&eacute;rieur, aussi pourrait-on parler aussi d&rsquo;Extranet. Nous donnons des codes d&rsquo;acc&egrave;s aux ligues qui les diffusent aux responsables des clubs qui en font la demande. On y trouve &laquo; l&rsquo;annuaire locatif &raquo; de la M2L, c&rsquo;est-&agrave;-dire toutes les informations sur les structures h&eacute;berg&eacute;es, les occupants des bureaux, etc. On y trouve un acc&egrave;s &agrave; l&rsquo;ensemble des articles sportifs de cinq journaux r&eacute;gionaux,&nbsp;</span><span style="font-family: Calibri, sans-serif;"><em>l&rsquo;Est-R&eacute;publicain, le</em></span><span style="font-family: Calibri, sans-serif;">&nbsp;</span><span style="font-family: Calibri, sans-serif;"><em>R&eacute;publicain Lorrain</em></span><span style="font-family: Calibri, sans-serif;">,&nbsp;</span><span style="font-family: Calibri, sans-serif;"><em>Vosges Matin</em></span><span style="font-family: Calibri, sans-serif;">,&nbsp;</span><span style="font-family: Calibri, sans-serif;"><em>les Derni&egrave;res Nouvelles d'Alsace</em></span><span style="font-family: Calibri, sans-serif;">&nbsp;et&nbsp;</span><span style="font-family: Calibri, sans-serif;"><em>L'Alsace Le Pays</em></span><span style="font-family: Calibri, sans-serif;">, rendus accessibles quelques jours apr&egrave;s leur parution. Ce service qui nous co&ucirc;te environ 2000 &euro; par an permet aux ligues de compiler leur&nbsp;</span><span style="font-family: Calibri, sans-serif;"><em>press-book</em></span><span style="font-family: Calibri, sans-serif;">. Il fait partie de la prestation globale offerte aux h&eacute;berg&eacute;s. On y trouve bien &eacute;videmment l&rsquo;ensemble du syst&egrave;me de r&eacute;servation des locaux et un ensemble de ressources documentaires, sur les aspects juridiques du sport, les aspects m&eacute;dicaux, etc.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;"><em>Q. En conclusion, quel est le projet qui vous tient actuellement &agrave; c&oelig;ur ?</em></span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">R. Nous sommes constamment sur nos gardes en mati&egrave;re de lutte contre les virus et autres joyeuset&eacute;s informatiques. Notre objectif est de surveiller et de contr&ocirc;ler &agrave; partir d'une plate-forme de gestion des configurations les postes de M2L mais aussi ceux des structures h&eacute;berg&eacute;es et d'autre part de cloisonner au maximum&nbsp; les utilisateurs dans des r&eacute;seaux distincts. L&rsquo;informaticien vous l&rsquo;expliquerait mieux que moi.</span></p>
<p class="western" align="justify">&nbsp;</p>
<p class="western" align="justify"><span style="font-family: Calibri, sans-serif;">Nous souhaitons &eacute;galement favoriser la vid&eacute;oconf&eacute;rence, en permettant &agrave; certaines r&eacute;unions de se tenir en minimisant les d&eacute;placements des b&eacute;n&eacute;voles. Il existe bien un syst&egrave;me de remise d&rsquo;imp&ocirc;t pour ceux-ci, mais on ne sait pas si ce syst&egrave;me durera. Par contre, on sait que le prix de l&rsquo;essence n&rsquo;aura pas tendance &agrave; baisser dans les ann&eacute;es &agrave; venir.</span></p>
</div></div>
</div>
</html><?php include 'footer.php'; ?> <html>
</body>	
</html>