<?php include 'header.php'; ?>
<title>Présentation</title>
<div class="container-fluid">
    <div class="row">
      	<div class="col-lg-10 col-lg-offset-1">
			<h2 class="western titreService spaceClass" style="color: #FF4500">Présentation de la Maison des Ligues de Lorraine</h2>
			<p class="western spaceClass" align="justify">La Maison des Ligues de Lorraine (M2L) a pour mission de fournir des espaces et des services aux différentes ligues sportives régionales et à d'autres structures hébergées. La M2L est une structure financée par le Conseil Régional de Lorraine dont l'administration est déléguée au Comité Régional Olympique et Sportif de Lorraine (CROSL).</p>
			<h3 class="western spaceClass"><a name="__RefHeading___Toc294250834"></a>Interview de son directeur, M. Lucien Sapin.</h3>
			<p class="western spaceClass" align="justify"><em>Q. M. Sapin, merci de nous accueillir dans ces locaux tous neufs et superbes de l'extension de la Maison des Ligues de Lorraine. Pouvez-vous nous dire quel est le statut juridique de cette maison, et quelles sont ses sources de financement ?</em></p>
			<p class="western spaceClass" align="justify">R. La Maison des Ligues est un établissement du Conseil Régional. Ce n'est pas une entité juridique en propre. Elle est financée à 100 % (pour son fonctionnement et pour la construction récente de l'extension des bâtiments C et D) par le Conseil Régional et sans aucune participation du Conseil Général de Meurthe et Moselle, bien qu'elle abrite un certain nombre de comités départementaux. Une convention de cogestion a été passée entre le Conseil Régional et le Comité Régional Olympique et Sportif de Lorraine pour la gestion de l'outil "Maison des Ligues". Le CROSL est une association financée par le ministère via le CNDS (Centre National de Développement du Sport).</p>
			<p class="western spaceClass" align="justify"><em>Q. Pourquoi l'hébergement de comités départementaux perdure-t-il ?</em></p>
			<p class="western spaceClass" align="justify">R. Lors de la reprise de la Maison des Ligues en 2000 par la Région Lorraine et la négociation qui en a suivi, le mouvement sportif a défendu la présence des comités départementaux dans les locaux existants. Cette présence est remise en question régulièrement, mais il est probable que rien ne sera fait avant la réforme des territoires et la "fusion" des conseillers régionaux et généraux en conseillers territoriaux.</p>
			<p class="western spaceClass" align="justify"><em>Q. Quelles sont les structures que vous hébergez ?</em></p>
			<p class="western spaceClass" align="justify">R. La Maison héberge la majorité des ligues sportives régionales, de la ligue de tennis (la plus grosse, qui emploie 8 personnes) à des ligues de sports qui n'ont pas d'employés permanents, comme le bowling ou la plongée sous-marine. La ligue de football occupe 2000 m<sup>2</sup> de bureaux dans la banlieue de Nancy et ne sera probablement jamais hébergée dans nos locaux. Nous hébergeons également, comme je vous le disais, quelques comités départementaux, ainsi que le CROSL et sa déclinaison départementale: le CDOS (Comité Départemental Olympique et Sportif).</p>
			<p class="western spaceClass" align="justify"><em>Q. Existe-il une convention d'hébergement ?</em></p>
			<p class="western spaceClass" align="justify">R. Oui, la convention initiale date de 2003. On parle de convention d'occupation du domaine public. Elle est en cours de révision, puisque les locaux ont été agrandis et que de nouveaux services sont apparus. La nouvelle version sera disponible l'été prochain, elle est assortie d'un règlement intérieur. Dans cette convention figure notamment l'obligation d'assurances en responsabilité civile des structures hébergées. Je peux vous donner un exemple de cette convention.</p>
			<p class="western spaceClass" align="justify"><em>Q. Quelle est la nature du "loyer" demandé aux "locataires" ?</em></p>
			<p class="western spaceClass" align="justify">R.On est davantage sur le principe d'une participation aux charges de gestion courante, plutôt que sur celui d'un loyer à proprement parler. On est sur la base de 5&euro; par m<sup>2</sup> et par mois, avec une augmentation prévue d'un euro dans les mois à venir. Un appel est effectué sur cette base forfaitaire en début d'année et une régularisation pourrait être demandée en fin d'année en cas de dépassement de la consommation électrique, mais cela n'a jamais été fait jusqu'à maintenant.</p>
			<p class="western spaceClass" align="justify">La réalité des charges à répartir est difficile à cerner. Si vous prenez par exemple le poste "nettoyage des locaux" : celui-ci fait l'objet d'un appel d'offres du Conseil Régional pour l'ensemble de ses implantations. Il est difficile de savoir quelle est la part affectée à la Maison et encore moins la part qui incomberait aux structures hébergées. Il n'y a pas eu jusqu'à maintenant de comptabilité analytique dans ce domaine.</p>
			<p class="western spaceClass" align="justify">Les charges comprennent le chauffage, l'électricité, le nettoyage, l'accès Internet; le téléphone n'en fait pas partie. Les consommations sont refacturées chaque trimestre aux structures hébergées. Depuis la mise en place de la téléphonie IP fin 2010, on peut connaître les consommations poste par poste et même structure par structure. Les appareils téléphoniques font partie de la prestation d'hébergement, comme la fourniture de trois badges pour l'entrée et de deux clés par bureau.</p>
			<p class="western spaceClass"><em>Q. Qui facture les prestations d'hébergement et les prestations annexes aux structures ?</em></p>
			<p class="western spaceClass" align="justify">R. Nous sommes dans le cadre d'une convention de cogestion entre le CROSL et la Région Lorraine, mais il n'est pas question que le CROSL facture l'utilisation de ressources appartenant à la Région, comme les locaux ou le téléphone par exemple. Par contre, le CROSL facture des prestations annexes réalisées sur des équipements lui appartenant, comme l'affranchissement et les tirages sur les photocopieurs numériques.</p>
			<p class="western spaceClass" align="justify"><em>Q. Comment fonctionne le système de réservation des salles ressources, comme les salles de réunions, l'amphithéâtre ou encore la nouvelle salle de convivialité ?</em></p>
			<p class="western spaceClass" align="justify">R. Concernant l'amphi, il y a &frac12; journée gratuite par an pour chaque ligue et comité départemental (CD). Les salles de réunions d'étage sont mises librement à la disposition des occupants de l'étage. Les salles de réunions sont réservables via l'Intranet, avec différents services associés dont certains sont payants. Il existe quatre niveaux de tarification. En 2009, nous avons reçu 2732 réunions et 47316 personnes ont assisté à ces réunions.</p>
			<p class="western spaceClass" align="justify"><em>Q. Quels sont ces niveaux de tarification ?</em></p>
			<p class="western spaceClass" align="justify">R. Les ligues peuvent réserver sans payer jusqu'à concurrence de six réservations par an, hors amphi. Les clubs sportifs et les comités départementaux ont un premier niveau de tarification. Les associations, les lycées ou encore les collèges sont sur un second niveau de tarification. Enfin, tous les autres organismes, y compris des sociétés privées, sont sur le niveau de tarification le plus haut. Pour toutes les structures qui ne sont pas hébergées, les locaux étant publics, il faut faire signer entre les parties une "convention d'occupation temporaire". La réservation se fait dans l'Intranet directement pour les structures hébergées ou par le secrétariat pour une demande extérieure. Les informations sont ensuite transmises au Conseil Régional qui émet un "titre de paiement", c'est-à-dire une facture d'occupation de locaux. Ces titres sont envoyés directement par le Conseil Régional aux utilisateurs.</p>
			<p class="western spaceClass" align="justify"><em>Q. Pouvez-vous nous parler du personnel de la M2L et de leurs missions ?</em></p>
			<p class="western spaceClass" align="justify">R. Les personnes qui travaillent ici sont de différentes catégories. Il y a d'abord ceux que j'appelle les "professionnels". Il y a deux employés du Conseil Régional (des factotums). Il y a sept ETP (équivalents Temps Plein) employés par le CROSL ; il y a le personnel des prestataires (gardiennage, ménage) et les salariés des ligues. Ensuite, il y a les bénévoles qui sont les élus des associations : CROSL, CDOS, ligues, comités départementaux. Il y a également les élus du Conseil Régional et enfin tous les autres : visiteurs, stagiaires, etc.</p>
			<p class="western spaceClass" align="justify"><em>Q. Quelles sont les missions des personnels "Région" et "CROSL" ?</em></p>
			<p class="western" align="justify">R. Nous avons 2,25 ETP "région", les deux factotums dont je vous parlais précédemment, et moi, qui suis employé, pour un quart de mon poste, par le conseil régional. Cela s'explique par le fait que je ne pourrais avoir logiquement d'autorité sur les personnels "Région" si je n'en fais pas partie moi-même.</p>
			<p class="western" align="justify">Les autres ETP du CROSL sont les suivants :</p>
			<p class="western" align="justify">- 0,75 ETP pour le poste de direction, comme je viens de vous dire</p>
			<p class="western" align="justify">- 0,8 ETP sur le suivi du Plan Impact Emploi Association</p>
			<p class="western" align="justify">- 0,5 ETP sur la gestion : facturation du CROSL et du Conseil Régional, comptabilité, gestion des réservations</p>
			<p class="western" align="justify">- 1 ETP sur la formation, la communication et le secrétariat</p>
			<p class="western" align="justify">- 0,80 ETP sur le domaine "SAPHIR", c'est-à-dire les aspects médicaux liés aux mouvements sportifs</p>
			<p class="western" align="justify">- 1 ETP d'infographiste et gestion des photocopieuses numériques.</p>
			<p class="western spaceClass" align="justify">- 1 ETP sur l'accueil qui va bientôt passer en deux fois 0,5 ETP.</p>
			<p class="western spaceClass" align="justify"><em>Q. Vous parliez du Plan Impact Emploi Association. De quoi s'agit-il ?</em></p>
			<p class="western spaceClass" align="justify">R. Ce dispositif répond à la volonté des pouvoirs publics de développer, en faveur des associations, une gamme de simplifications et de services en matière d'aide à l'emploi, comme la gestion des paies et l'assistance comptable. Ce service est offert à toutes les associations de moins de 10 ETP : clubs sportifs, associations culturelles, etc. <em>Impact Emploi</em> est un logiciel développé par l' URSSAF qui permet d'établir le bulletin de salaire et de fournir l'ensemble des déclarations sociales et fiscales, qu'elles soient mensuelles, trimestrielles ou annuelles. Tout cela, simplement à partir de quelques données : le nombre d'heures travaillées, leur nature et les éléments de rémunération bruts ou nets (salaire, prime, avantages en nature, indemnités de frais, etc.). Ce logiciel est confié gratuitement à des tiers de confiance qui exécutent les opérations pour le compte de l'association. Le tiers de confiance est souvent une structure qui fédère le milieu dans lequel évolue l'association. Ainsi, le CROSL a reçu le label "CRIB" (Centre de Ressources et d'Information des Bénévoles) pour devenir tiers de confiance pour l'URSSAF qui met à notre disposition ce fameux logiciel. Nous demandons 60 &euro; de cotisation annuelle par association et nous facturons 5 &euro; par fiche de paie. Nous produisons bien évidemment toute la panoplie légale de documents : récapitulatifs périodiques, déclarations URSSAF et ASSEDIC, organismes de retraite. Nous pouvons gérer des virements automatiques : prélèvement sur le compte des associations et versement sur le compte des salariés ou encore prélèvement direct sur les comptes des associations au crédit des organismes sociaux. En 2009, nous avions 72 associations abonnées pour un total de 332 salariés, ce qui représentait 2,8 millions d'euros de masse salariale, soit 15 % de la masse salariale totale du sport lorrain.</p>
			<p class="western" align="justify">En tant que centre labellisé "CRIB" nous apportons également des conseils aux associations qui emploient du personnel. Ces conseils portent sur le respect de la législation, sur le remboursement des déplacements, sur les litiges éventuels. Nous disposons de toute l'information utile pour mener à bien cette mission de conseil.</p>
			<p class="western spaceClass" align="justify"><br />En ce moment, sous l'impulsion du ministère, nous &oelig;uvrons au développement de l'usage du chèque emploi associatif.</p>
			<p class="western spaceClass" align="justify"><em>Q. Comment sont gérés les appels d'offres aux prestataires ?</em></p>
			<p class="western spaceClass" align="justify">R. Le CROSL n'est pas soumis à l'obligation des marchés publics, contrairement à la Région. Les appels d'offres "Région" sont pilotés directement par les services du Conseil Régional. Les appels d'offres du CROSL sont gérés directement par moi. En général, nous faisons établir quelques devis et nous choisissons nos prestataires sur la base de ces devis. Pour les nombreux projets concernant l'informatique, je me fais assister d'un informaticien bénévole, membre du bureau du CROSL. La réalisation des projets est en général confiée à des prestataires locaux. Notre informaticien bénévole ne s'occupe que de petits travaux quotidiens d'assistance aux utilisateurs.</p>
			<p class="western spaceClass" align="justify"><em>Q. Avez-vous un exemple de projet, l'Intranet ou le réseau d'affichage numérique ?</em></p>
			<p class="western spaceClass" align="justify">R. C'est typiquement un projet mixte. Les téléviseurs du réseau d'information numérique ont été fournis par la Région dans le cadre d'un appel d'offre public. Le système qui fait paraître les informations sur les afficheurs a fait l'objet d'une consultation et c'est la société qui nous avait fourni l'Intranet, il y a quelques années, qui a été choisie pour développer ce logiciel qui récupère directement les données du système de réservation des salles. Il n'est donc pas nécessaire de ressaisir les informations sur l'utilisation des salles.</p>
			<p class="western spaceClass" align="justify"><em>Q. Quelles sont les autres fonctions de l'Intranet ?</em></p>
			<p class="western spaceClass" align="justify">R. Comme vous le savez, c'est un Intranet accessible également de l'extérieur, aussi pourrait-on parler aussi d'Extranet. Nous donnons des codes d'accès aux ligues qui les diffusent aux responsables des clubs qui en font la demande. On y trouve "l'annuaire locatif" de la M2L, c'est-à-dire toutes les informations sur les structures hébergées, les occupants des bureaux, etc. On y trouve un accès à l'ensemble des articles sportifs de cinq journaux régionaux, <em>l'Est-Républicain, le</em> <em>Républicain Lorrain</em>, <em>Vosges Matin</em>, <em>les Dernières Nouvelles d'Alsace</em> et <em>L'Alsace Le Pays</em>, rendus accessibles quelques jours après leur parution. Ce service qui nous coûte environ 2000 &euro; par an permet aux ligues de compiler leur <em>press-book</em>. Il fait partie de la prestation globale offerte aux hébergés. On y trouve bien évidemment l'ensemble du système de réservation des locaux et un ensemble de ressources documentaires, sur les aspects juridiques du sport, les aspects médicaux, etc.</p>
			<p class="western spaceClass" align="justify"><em>Q. En conclusion, quel est le projet qui vous tient actuellement à c&oelig;ur ?</em></p>
			<p class="western spaceClass" align="justify">R. Nous sommes constamment sur nos gardes en matière de lutte contre les virus et autres joyeusetés informatiques. Notre objectif est de surveiller et de contrôler à partir d'une plate-forme de gestion des configurations les postes de M2L mais aussi ceux des structures hébergées et d'autre part de cloisonner au maximum  les utilisateurs dans des réseaux distincts. L'informaticien vous l'expliquerait mieux que moi.</p>
			<p class="western" align="justify">Nous souhaitons également favoriser la vidéoconférence, en permettant à certaines réunions de se tenir en minimisant les déplacements des bénévoles. Il existe bien un système de remise d'impôt pour ceux-ci, mais on ne sait pas si ce système durera. Par contre, on sait que le prix de l'essence n'aura pas tendance à baisser dans les années à venir.</p>
		</div>	
	</div>
</div>
<?php include 'footer.php'; ?>